# Generated by Django 3.2.5 on 2021-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisticmovements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_movement',
            field=models.ManyToManyField(help_text='Select an art movement for this artwork', null=True, to='artisticmovements.ArtMovement'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
