# Generated by Django 3.2.5 on 2021-10-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisticmovements', '0002_auto_20211017_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_movement',
            field=models.ManyToManyField(help_text='Select an art movement for this artwork', to='artisticmovements.ArtMovement'),
        ),
    ]
