# Generated by Django 3.2.5 on 2021-10-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisticmovements', '0003_alter_artwork_art_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_movement',
            field=models.ManyToManyField(blank=True, help_text='Select an art movement for this artwork', to='artisticmovements.ArtMovement'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisticmovements.artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
