# Generated by Django 3.2.5 on 2021-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisticmovements', '0004_auto_20211020_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='uploaded_by_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
