# Generated by Django 3.2.5 on 2022-01-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisticmovements', '0010_auto_20220131_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='created_on',
        ),
    ]
