# Generated by Django 3.2.5 on 2022-01-31 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisticmovements', '0011_auto_20220131_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='appreciated_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
